options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/dock-init', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/dock-init']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
    - 'run'
    - 'deploy'
    - 'dock-init'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/dock-init'
    - '--region'
    - 'global'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

substitutions:
  _LOCATION: 'global'
  _REPOSITORY: 'dock-init'
