# Specify global options for the build
options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging instead of Cloud Storage for logs

# Define the sequence of build steps
steps:
  # Step 1: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'  # Use Google's Docker builder image
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/dock-init/dock-init'
      - '--build-arg'
      - 'NODE_ENV=production'
      - '.'
    id: 'build-and-push'
    waitFor: ['-']  # Start immediately
  
  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'  # Use Cloud SDK for deployment
    entrypoint: 'gcloud'  # Use gcloud command
    args:
    - 'run'
    - 'deploy'
    - 'dock-init'
    - '--image'
    - 'gcr.io/dock-init/dock-init'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--command=npm'
    - '--args=start'
    id: 'deploy'
    waitFor: ['build-and-push']  # Wait for first step to complete

# Set timeout for the entire build
timeout: '1200s'  # 20 minutes

