options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/dock-init/dock-init', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dock-init/dock-init']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'dock-init'
    - '--image'
    - 'gcr.io/dock-init/dock-init'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--no-cpu-throttling'
    - '--min-instances=1'
    - '--port=3000'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
    - 'run'
    - 'services'
    - 'add-iam-policy-binding'
    - 'dock-init'
    - '--region=us-central1'
    - '--member=allUsers'
    - '--role=roles/run.invoker'

serviceAccount: 'projects/dock-init/serviceAccounts/dock-init@cloudbuild.gserviceaccount.com'

